/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as PoliticadeprivacidadeRouteImport } from './routes/politicadeprivacidade'
import { Route as ExclusaodedadosRouteImport } from './routes/exclusaodedados'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedLancamentosRouteImport } from './routes/_authenticated/lancamentos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAparenciaRouteImport } from './routes/_authenticated/aparencia'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiPublicMetaCallbackRouteImport } from './routes/api/public/meta/callback'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticadeprivacidadeRoute = PoliticadeprivacidadeRouteImport.update({
  id: '/politicadeprivacidade',
  path: '/politicadeprivacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ExclusaodedadosRoute = ExclusaodedadosRouteImport.update({
  id: '/exclusaodedados',
  path: '/exclusaodedados',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMetasRoute = AuthenticatedMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLancamentosRoute =
  AuthenticatedLancamentosRouteImport.update({
    id: '/lancamentos',
    path: '/lancamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAparenciaRoute = AuthenticatedAparenciaRouteImport.update({
  id: '/aparencia',
  path: '/aparencia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMetaCallbackRoute = ApiPublicMetaCallbackRouteImport.update({
  id: '/api/public/meta/callback',
  path: '/api/public/meta/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cadastro': typeof CadastroRoute
  '/exclusaodedados': typeof ExclusaodedadosRoute
  '/politicadeprivacidade': typeof PoliticadeprivacidadeRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/aparencia': typeof AuthenticatedAparenciaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/lancamentos': typeof AuthenticatedLancamentosRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/public/meta/callback': typeof ApiPublicMetaCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cadastro': typeof CadastroRoute
  '/exclusaodedados': typeof ExclusaodedadosRoute
  '/politicadeprivacidade': typeof PoliticadeprivacidadeRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/aparencia': typeof AuthenticatedAparenciaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/lancamentos': typeof AuthenticatedLancamentosRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/public/meta/callback': typeof ApiPublicMetaCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cadastro': typeof CadastroRoute
  '/exclusaodedados': typeof ExclusaodedadosRoute
  '/politicadeprivacidade': typeof PoliticadeprivacidadeRoute
  '/termos': typeof TermosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/aparencia': typeof AuthenticatedAparenciaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/lancamentos': typeof AuthenticatedLancamentosRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/public/meta/callback': typeof ApiPublicMetaCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cadastro'
    | '/exclusaodedados'
    | '/politicadeprivacidade'
    | '/termos'
    | '/admin'
    | '/aparencia'
    | '/dashboard'
    | '/lancamentos'
    | '/metas'
    | '/api/stripe/webhook'
    | '/api/public/meta/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cadastro'
    | '/exclusaodedados'
    | '/politicadeprivacidade'
    | '/termos'
    | '/admin'
    | '/aparencia'
    | '/dashboard'
    | '/lancamentos'
    | '/metas'
    | '/api/stripe/webhook'
    | '/api/public/meta/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cadastro'
    | '/exclusaodedados'
    | '/politicadeprivacidade'
    | '/termos'
    | '/_authenticated/admin'
    | '/_authenticated/aparencia'
    | '/_authenticated/dashboard'
    | '/_authenticated/lancamentos'
    | '/_authenticated/metas'
    | '/api/stripe/webhook'
    | '/api/public/meta/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CadastroRoute: typeof CadastroRoute
  ExclusaodedadosRoute: typeof ExclusaodedadosRoute
  PoliticadeprivacidadeRoute: typeof PoliticadeprivacidadeRoute
  TermosRoute: typeof TermosRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiPublicMetaCallbackRoute: typeof ApiPublicMetaCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politicadeprivacidade': {
      id: '/politicadeprivacidade'
      path: '/politicadeprivacidade'
      fullPath: '/politicadeprivacidade'
      preLoaderRoute: typeof PoliticadeprivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exclusaodedados': {
      id: '/exclusaodedados'
      path: '/exclusaodedados'
      fullPath: '/exclusaodedados'
      preLoaderRoute: typeof ExclusaodedadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lancamentos': {
      id: '/_authenticated/lancamentos'
      path: '/lancamentos'
      fullPath: '/lancamentos'
      preLoaderRoute: typeof AuthenticatedLancamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aparencia': {
      id: '/_authenticated/aparencia'
      path: '/aparencia'
      fullPath: '/aparencia'
      preLoaderRoute: typeof AuthenticatedAparenciaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta/callback': {
      id: '/api/public/meta/callback'
      path: '/api/public/meta/callback'
      fullPath: '/api/public/meta/callback'
      preLoaderRoute: typeof ApiPublicMetaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAparenciaRoute: typeof AuthenticatedAparenciaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLancamentosRoute: typeof AuthenticatedLancamentosRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAparenciaRoute: AuthenticatedAparenciaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLancamentosRoute: AuthenticatedLancamentosRoute,
  AuthenticatedMetasRoute: AuthenticatedMetasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CadastroRoute: CadastroRoute,
  ExclusaodedadosRoute: ExclusaodedadosRoute,
  PoliticadeprivacidadeRoute: PoliticadeprivacidadeRoute,
  TermosRoute: TermosRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiPublicMetaCallbackRoute: ApiPublicMetaCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
